### ISSUE TITLE
Interop with commonjs?

### ISSUE THREAD

**Issue by xtuc** [WebAssembly/esm-integration#10]
We need to keep in mind that currently JavaScript Modules are mostly transpiled to commonjs.

While most of the bundlers also understand ESM and handle it accordingly, some environment like Node have a strong dependency on commonjs and transpiled distributed modules.

This is not really an issue since I think that we would handle them transparently (especially if #9 is not permitted). I just wanted to make you aware of that and we also should make it clear in the documentation.

**Comment by linclark** [comment]
Interop between CommonJS and ES modules is being handled by the Node modules WG. I am a participant in that WG and have been updating them on the progress of the wasm modules effort, as is noted in the presentation linked from the proposal. I will continue to keep them updated. Since no additional action needs to be taken on this, I'm going to close it out.
